# This uses newer and faster docker based build system
sudo: false

language: php

php:
  - nightly # PHP 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - ./composer.phar install --dev --prefer-source --no-interaction

script:
  - phpcs --standard=PSR2 ./**/*.php
